//! RESQD on-chain canary anchoring client.
//!
//! Wraps the `ResqdCanaryAnchor` Solidity contract deployed on Base L2.
//! Every [`resqd_core::canary::CanaryChain::rotate()`] produces a
//! [`resqd_core::canary::CanaryCommitment`] that MUST be anchored on-chain
//! before the access is considered valid. This crate is the service-side
//! bridge between the Rust canary chain and the Ethereum-compatible chain.
//!
//! The chain enforces monotonic sequence + prev-hash linkage identically to
//! [`resqd_core::canary::CanaryChain::verify_chain`], so the on-chain state
//! mirrors the off-chain state. Any divergence is a tamper signal.

use alloy::{
    network::{Ethereum, EthereumWallet},
    primitives::{Address, B256, FixedBytes},
    providers::{DynProvider, Provider, ProviderBuilder},
    rpc::types::TransactionReceipt,
    signers::local::PrivateKeySigner,
    sol,
    transports::http::reqwest::Url,
};
use resqd_core::canary::CanaryCommitment;
use resqd_core::crypto::hash::AssetHash;

mod error;
pub use error::{ChainError, Result};

// ---------------------------------------------------------------------------
//               Solidity binding (generated by alloy::sol!)
// ---------------------------------------------------------------------------

sol! {
    #[sol(rpc)]
    #[allow(missing_docs)]
    contract ResqdCanaryAnchor {
        error NotOwner();
        error NotAuthorizedSigner();
        error InvalidSequence(uint64 expected, uint64 provided);
        error PrevHashMismatch(bytes32 expected, bytes32 provided);
        error FirstAnchorMustBeZero();

        event CanaryAnchored(
            bytes32 indexed assetId,
            bytes32 commitmentHash,
            uint64 sequence,
            uint64 timestamp,
            bytes32 prevHash
        );
        event SignerAuthorized(address indexed signer);
        event SignerRevoked(address indexed signer);

        function owner() external view returns (address);
        function authorizedSigners(address) external view returns (bool);
        function authorizeSigner(address signer) external;
        function revokeSigner(address signer) external;
        function anchor(
            bytes32 assetId,
            bytes32 commitmentHash,
            uint64 sequence,
            bytes32 prevHash
        ) external;
        function getAnchor(bytes32 assetId) external view returns (
            bytes32 commitmentHash,
            uint64 sequence,
            uint64 timestamp,
            bool exists
        );
        function verifyAccessCount(bytes32 assetId, uint64 expectedCount) external view returns (bool);
        function verifyCurrentCommitment(bytes32 assetId, bytes32 expectedHash) external view returns (bool);
    }
}

// ---------------------------------------------------------------------------
//                             Config
// ---------------------------------------------------------------------------

/// Chain configuration for the anchor client.
#[derive(Clone, Debug)]
pub struct ChainConfig {
    /// HTTP RPC URL (e.g. `https://mainnet.base.org`, `https://sepolia.base.org`,
    /// or a local `http://127.0.0.1:8545` anvil instance for tests).
    pub rpc_url: Url,
    /// Deployed contract address.
    pub contract: Address,
    /// Private key of an authorized signer (hex, with or without `0x` prefix).
    pub signer_key: String,
}

impl ChainConfig {
    /// Build from environment variables.
    ///
    /// - `RESQD_CHAIN_RPC_URL`
    /// - `RESQD_CHAIN_CONTRACT`
    /// - `RESQD_CHAIN_SIGNER_KEY`
    pub fn from_env() -> Result<Self> {
        let rpc_url = std::env::var("RESQD_CHAIN_RPC_URL")
            .map_err(|_| ChainError::MissingEnv("RESQD_CHAIN_RPC_URL"))?
            .parse::<Url>()
            .map_err(|e| ChainError::InvalidConfig(format!("RESQD_CHAIN_RPC_URL: {e}")))?;
        let contract: Address = std::env::var("RESQD_CHAIN_CONTRACT")
            .map_err(|_| ChainError::MissingEnv("RESQD_CHAIN_CONTRACT"))?
            .parse()
            .map_err(|e| ChainError::InvalidConfig(format!("RESQD_CHAIN_CONTRACT: {e}")))?;
        let signer_key = std::env::var("RESQD_CHAIN_SIGNER_KEY")
            .map_err(|_| ChainError::MissingEnv("RESQD_CHAIN_SIGNER_KEY"))?;
        Ok(Self { rpc_url, contract, signer_key })
    }
}

// ---------------------------------------------------------------------------
//                        Client
// ---------------------------------------------------------------------------

/// The current on-chain anchor state for an asset.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AnchorState {
    pub commitment_hash: [u8; 32],
    pub sequence: u64,
    pub timestamp: u64,
    pub exists: bool,
}

/// Client for the `ResqdCanaryAnchor` contract.
///
/// Wraps an alloy provider + signer and exposes typed methods that accept
/// resqd-core types where possible. Cheap to clone — internal provider is
/// `Arc`-shared and its nonce filler is memoized across calls, so sending
/// multiple transactions back-to-back reuses the same nonce counter instead
/// of restarting from the chain state on every call.
#[derive(Clone)]
pub struct CanaryAnchorClient {
    contract: Address,
    provider: DynProvider<Ethereum>,
}

impl CanaryAnchorClient {
    /// Build a client from [`ChainConfig`].
    pub fn new(config: ChainConfig) -> Result<Self> {
        let signer: PrivateKeySigner = config
            .signer_key
            .parse()
            .map_err(|e| ChainError::InvalidConfig(format!("signer key: {e}")))?;
        let wallet = EthereumWallet::from(signer);
        let provider = ProviderBuilder::new()
            .wallet(wallet)
            .connect_http(config.rpc_url)
            .erased();
        Ok(Self {
            contract: config.contract,
            provider,
        })
    }

    fn provider(&self) -> &DynProvider<Ethereum> {
        &self.provider
    }

    /// Anchor a canary commitment on-chain.
    ///
    /// `asset_id_hash` is the BLAKE3 hash of the resqd asset identifier — use
    /// [`asset_id_to_bytes32`] to convert a [`resqd_core::crypto::hash::AssetHash`].
    /// `commitment` comes from [`resqd_core::canary::CanaryChain::rotate`]
    /// (or `commitments[0]` for the first upload).
    ///
    /// Returns the transaction receipt (which contains the mined block number
    /// and the emitted `CanaryAnchored` event).
    pub async fn anchor_commitment(
        &self,
        asset_id_hash: [u8; 32],
        commitment: &CanaryCommitment,
    ) -> Result<TransactionReceipt> {
        let provider = self.provider();
        let contract = ResqdCanaryAnchor::new(self.contract, &provider);

        let prev_hash: [u8; 32] = commitment
            .prev_hash
            .as_ref()
            .map(asset_hash_to_bytes32)
            .unwrap_or([0u8; 32]);

        // Explicit gas limit bypasses eth_estimateGas. Two reasons:
        //   1. Max observed anchor gas is 71,754 (first-write) / 38,177
        //      (rotation). 200k is 3x headroom, cheap on Base L2.
        //   2. eth_estimateGas errors ambiguously when the call would
        //      revert — hard for callers (and tests) to distinguish from
        //      RPC failures. By skipping estimation we get a clean
        //      reverted-receipt that surfaces as a proper error below.
        let receipt = contract
            .anchor(
                FixedBytes(asset_id_hash),
                FixedBytes(asset_hash_to_bytes32(&commitment.hash)),
                commitment.sequence,
                FixedBytes(prev_hash),
            )
            .gas(200_000)
            .send()
            .await
            .map_err(|e| ChainError::ContractCall(format!("anchor(): {e}")))?
            .get_receipt()
            .await
            .map_err(|e| ChainError::ContractCall(format!("anchor() receipt: {e}")))?;

        if !receipt.status() {
            return Err(ChainError::ContractCall(format!(
                "anchor() reverted on-chain: tx {:?}",
                receipt.transaction_hash
            )));
        }

        Ok(receipt)
    }

    /// Read the current on-chain state for an asset.
    pub async fn get_anchor(&self, asset_id_hash: [u8; 32]) -> Result<AnchorState> {
        let provider = self.provider();
        let contract = ResqdCanaryAnchor::new(self.contract, &provider);

        let result = contract
            .getAnchor(FixedBytes(asset_id_hash))
            .call()
            .await
            .map_err(|e| ChainError::ContractCall(format!("getAnchor(): {e}")))?;

        Ok(AnchorState {
            commitment_hash: result.commitmentHash.0,
            sequence: result.sequence,
            timestamp: result.timestamp,
            exists: result.exists,
        })
    }

    /// Verify the on-chain access count matches an expected value.
    pub async fn verify_access_count(
        &self,
        asset_id_hash: [u8; 32],
        expected_count: u64,
    ) -> Result<bool> {
        let provider = self.provider();
        let contract = ResqdCanaryAnchor::new(self.contract, &provider);

        let ok = contract
            .verifyAccessCount(FixedBytes(asset_id_hash), expected_count)
            .call()
            .await
            .map_err(|e| ChainError::ContractCall(format!("verifyAccessCount(): {e}")))?;
        Ok(ok)
    }

    /// Authorize another signer (owner-only on-chain check).
    pub async fn authorize_signer(&self, signer: Address) -> Result<TransactionReceipt> {
        let provider = self.provider();
        let contract = ResqdCanaryAnchor::new(self.contract, &provider);
        let receipt = contract
            .authorizeSigner(signer)
            .send()
            .await
            .map_err(|e| ChainError::ContractCall(format!("authorizeSigner(): {e}")))?
            .get_receipt()
            .await
            .map_err(|e| ChainError::ContractCall(format!("authorizeSigner() receipt: {e}")))?;
        Ok(receipt)
    }

    /// Contract address this client is bound to.
    pub fn contract_address(&self) -> Address {
        self.contract
    }
}

// ---------------------------------------------------------------------------
//                         Helpers
// ---------------------------------------------------------------------------

/// Convert an [`AssetHash`] (BLAKE3, 32 bytes) to a 32-byte array suitable
/// for bytes32 on-chain.
pub fn asset_hash_to_bytes32(h: &AssetHash) -> [u8; 32] {
    h.0
}

/// Convert a bytes32 back to AssetHash.
pub fn bytes32_to_asset_hash(b: [u8; 32]) -> AssetHash {
    AssetHash(b)
}

/// Convert a 32-byte array to alloy's `B256`.
pub fn bytes32_to_b256(b: [u8; 32]) -> B256 {
    B256::from(b)
}
