/**
 * Recovery passphrase client.
 *
 * The passphrase fallback exists for devices without WebAuthn PRF
 * support — primarily iOS Safari as of 2026. Instead of deriving the
 * master key from a hardware-backed PRF output, we derive a KEK
 * (key-encrypting key) from a user-chosen passphrase via Argon2id,
 * wrap the master key under that KEK via XChaCha20-Poly1305, and
 * store the ciphertext on the server. Unlocking on a non-PRF device
 * is the mirror: download the blob, prompt for the passphrase,
 * re-derive the KEK, decrypt.
 *
 * Security posture:
 *
 * - The server never sees the passphrase, the KEK, or the master key.
 *   It only sees a sealed envelope it cannot decrypt.
 * - A weak passphrase weakens the whole vault to "as strong as the
 *   passphrase." A strong random passphrase (generated by a password
 *   manager) is effectively as strong as the master key itself. The
 *   Settings UI must push users toward password managers.
 * - Argon2id parameters are pinned to the core crate's defaults via
 *   the `recovery_kdf` tag. Changing params is a breaking change that
 *   requires a migration with both old and new tags supported
 *   simultaneously for a window.
 * - Enabling the passphrase is always reversible via
 *   `deleteRecoveryPassphrase()` — but deleting it from a device that
 *   can't PRF-unlock the vault would immediately lock the user out.
 */

import { API_URL, getCrypto, bytesToBase64, base64ToBytes } from "./resqdCrypto";

/** Minimum passphrase length, enforced in the UI. 12 is the floor
 *  Kevin picked; below this the strength estimator treats even the
 *  best character-class mix as insufficient. */
export const MIN_PASSPHRASE_LENGTH = 12;

/** KDF tag currently accepted by the server. Matches `RECOVERY_KDF_CURRENT`
 *  in `api/src/auth.rs`. Bump in lockstep with the server if Argon2
 *  parameters change. */
export const RECOVERY_KDF_TAG = "argon2id-default";

/** Shape returned by `GET /auth/me/recovery-blob`. */
export interface RecoveryBlob {
  recovery_blob_b64: string;
  recovery_salt_b64: string;
  recovery_kdf: string;
}

/** Bucketed strength summary shown next to the passphrase input. */
export interface PassphraseStrength {
  /** 0 = too short / unusable, 1 = weak, 2 = fair, 3 = good, 4 = strong. */
  score: 0 | 1 | 2 | 3 | 4;
  /** Short label for the UI ("weak", "strong", etc.). */
  label: string;
  /** Rough Shannon-entropy estimate in bits. */
  bits: number;
  /** Passes the 12-char minimum length floor. */
  meetsMinimum: boolean;
}

/**
 * Rough-cut passphrase strength estimator.
 *
 * We estimate Shannon entropy as `length * log2(charset_size)`, where
 * charset_size grows with the number of character classes present
 * (lowercase, uppercase, digits, symbols). This is a conservative
 * approximation that assumes the passphrase is drawn from a random
 * distribution over the detected classes; it does NOT account for
 * dictionary words, predictable patterns, or leetspeak substitutions,
 * which is why we steer users toward password-manager-generated
 * passphrases in the UI copy.
 *
 * If we ever need tighter estimates, swap this out for zxcvbn —
 * ~14 KB gzipped, handles dictionaries and keyboard walks. For the
 * alpha, this rough estimate is sufficient to distinguish
 * "hunter2hunter2" from "Tr4vERsE!aDjacent-SOLenoiD-12!@".
 */
export function estimatePassphraseStrength(passphrase: string): PassphraseStrength {
  const len = passphrase.length;
  if (len === 0) {
    return { score: 0, label: "empty", bits: 0, meetsMinimum: false };
  }

  const meetsMinimum = len >= MIN_PASSPHRASE_LENGTH;

  let charset = 0;
  if (/[a-z]/.test(passphrase)) charset += 26;
  if (/[A-Z]/.test(passphrase)) charset += 26;
  if (/[0-9]/.test(passphrase)) charset += 10;
  if (/[^a-zA-Z0-9]/.test(passphrase)) charset += 32;
  if (charset === 0) charset = 1;

  const bits = Math.round(len * Math.log2(charset));

  // Below the minimum length we always report "too short" regardless
  // of entropy, to prevent users from trying to outwit the policy
  // with a handful of exotic symbols.
  if (!meetsMinimum) {
    return { score: 0, label: "too short", bits, meetsMinimum };
  }

  // Thresholds calibrated so a 12-char all-classes random
  // passphrase lands at ~78 bits = "fair", and a 20-char
  // all-classes random passphrase lands at ~131 bits = "strong".
  let score: 0 | 1 | 2 | 3 | 4;
  let label: string;
  if (bits < 50) {
    score = 1;
    label = "weak";
  } else if (bits < 75) {
    score = 2;
    label = "fair";
  } else if (bits < 100) {
    score = 3;
    label = "good";
  } else {
    score = 4;
    label = "strong";
  }
  return { score, label, bits, meetsMinimum };
}

/**
 * Wrap the current master key under a passphrase-derived KEK and
 * upload the resulting envelope to the server. Called from two
 * places:
 *
 * 1. A PRF-capable user opting in from Settings. They already hold
 *    the master key in `sessionStorage` — pass `loadMasterKey()` as
 *    the `masterKey` argument. After this call, the user can log in
 *    from an iPhone by downloading the blob and entering the
 *    passphrase.
 * 2. An iPhone-first signup flow. It generates a fresh random master
 *    key via `getCrypto().generate_random_key()`, passes that as
 *    `masterKey`, and stashes it in `sessionStorage` after the blob
 *    upload succeeds.
 *
 * Throws on network / validation error. Callers should catch and
 * surface the message; no retry is built in because retries make
 * sense only in specific UX flows.
 */
export async function setRecoveryPassphrase(
  passphrase: string,
  masterKey: Uint8Array,
): Promise<void> {
  if (passphrase.length < MIN_PASSPHRASE_LENGTH) {
    throw new Error(
      `passphrase must be at least ${MIN_PASSPHRASE_LENGTH} characters`,
    );
  }
  if (masterKey.length !== 32) {
    throw new Error(
      `master key must be 32 bytes, got ${masterKey.length}`,
    );
  }

  const crypto = await getCrypto();

  // Fresh salt on every set/rotate. An attacker who scraped an old
  // blob cannot replay old Argon2 precomputation against the new
  // envelope because the salt differs.
  const salt = crypto.generate_salt();

  // Derive the key-encrypting key. Argon2id is expensive by design —
  // expect ~500ms on a modern laptop, longer on a phone. Don't call
  // this in a loop.
  const kek = crypto.derive_key(passphrase, salt);

  // Wrap the master key as a standard XChaCha20-Poly1305 envelope.
  // `encrypt_data` returns a JSON string; base64-encode it to match
  // the existing `wrapped_privkey_x25519_b64` wire format.
  const envelopeJson = crypto.encrypt_data(kek, masterKey);
  const blobB64 = btoa(envelopeJson);
  const saltB64 = bytesToBase64(salt);

  const resp = await fetch(`${API_URL}/auth/me/recovery-blob`, {
    method: "PUT",
    credentials: "include",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      recovery_blob_b64: blobB64,
      recovery_salt_b64: saltB64,
      recovery_kdf: RECOVERY_KDF_TAG,
    }),
  });
  if (!resp.ok) {
    throw new Error(await readError(resp));
  }
}

/**
 * Download the current user's recovery blob. Returns `null` on 404
 * (the common case for users who haven't opted in). Throws on other
 * network / auth errors so callers can distinguish "not set" from
 * "something went wrong."
 */
export async function fetchRecoveryBlob(): Promise<RecoveryBlob | null> {
  const resp = await fetch(`${API_URL}/auth/me/recovery-blob`, {
    credentials: "include",
  });
  if (resp.status === 404) return null;
  if (!resp.ok) {
    throw new Error(await readError(resp));
  }
  return (await resp.json()) as RecoveryBlob;
}

/**
 * Unwrap a master key from a recovery blob given the passphrase.
 * Throws on wrong passphrase (AEAD auth failure) — the error is
 * intentionally non-specific because distinguishing "wrong
 * passphrase" from "corrupted blob" server-side would leak timing
 * info; the server doesn't know, and neither does this client. A
 * caught exception here should be shown to the user as "incorrect
 * passphrase" regardless of the actual failure mode.
 *
 * Passphrase validation against the blob happens purely client-side:
 * if Argon2id produces a KEK that decrypts the envelope, it was
 * correct.
 */
export async function unwrapMasterKey(
  blob: RecoveryBlob,
  passphrase: string,
): Promise<Uint8Array> {
  if (blob.recovery_kdf !== RECOVERY_KDF_TAG) {
    throw new Error(
      `unsupported recovery KDF: ${blob.recovery_kdf}. This vault was created by a newer client version; please update.`,
    );
  }

  const crypto = await getCrypto();
  const salt = base64ToBytes(blob.recovery_salt_b64);
  const kek = crypto.derive_key(passphrase, salt);

  const envelopeJson = atob(blob.recovery_blob_b64);
  // `decrypt_data` throws on AEAD tag mismatch. Surface a generic
  // message so users don't see a crypto-internal error.
  let masterKey: Uint8Array;
  try {
    masterKey = crypto.decrypt_data(kek, envelopeJson);
  } catch {
    throw new Error("incorrect passphrase");
  }

  if (masterKey.length !== 32) {
    throw new Error(
      `unwrapped master key has unexpected length ${masterKey.length} — vault may be corrupted`,
    );
  }
  return masterKey;
}

/**
 * Remove the recovery blob entirely. Called when a user decides to
 * go hardware-only after having previously set a passphrase. This
 * does NOT touch vault data; only the passphrase-unlockable envelope
 * is removed. If the user calls this and then loses access to their
 * PRF device, they are locked out of the vault with no recovery path.
 *
 * The UI should confirm destructively before calling this.
 */
export async function deleteRecoveryPassphrase(): Promise<void> {
  const resp = await fetch(`${API_URL}/auth/me/recovery-blob`, {
    method: "DELETE",
    credentials: "include",
  });
  if (!resp.ok) {
    throw new Error(await readError(resp));
  }
}

async function readError(resp: Response): Promise<string> {
  try {
    const j = (await resp.json()) as { error?: string };
    return j.error ?? `${resp.status} ${resp.statusText}`;
  } catch {
    return `${resp.status} ${resp.statusText}`;
  }
}
